### ISSUE TITLE
Getting to Know Your Audience

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/leadership_toolkit#12]
Standards and templates for developing content [can be found here](https://wiki.mozilla.org/Participation/Projects/Leadership_toolkit#Work_To_Date).

**Comment by emmairwin** [comment]
Added @jgmac1106 learning objectives to this file for collaboration and review:   https://docs.google.com/document/d/1b1xHKA4P76fCSAzHgalB5cxtMqz6WR5_dzk7Dk5EvD4/edit#

Still needs title, description and other information if we can come up with it, this will help reviewers.

**Comment by jgmac1106** [comment]
Here is a link to copy of the template. Will rectify versions once I get editing rights to original: https://docs.google.com/document/d/1sxJJzGQJV639tGQp-9W2oE1f6_6sWvJlLvgOM7qeX7g/edit?usp=sharing

**Comment by emmairwin** [comment]
@jgmac1106 thank you for this !

**Comment by emmairwin** [comment]
Approved - with some comments for guidance (we can collaborate easily), this was great work Greg - thank you SO MUCH.

**Comment by emmairwin** [comment]
@jgmac1106 Violation of our workflow process to put this up before you review - but doing it just to move things along I don't want to keep your work idling.

https://leadership.mozilla.community/method/know-your-audience/

Thoughts?  I feel the formatting isnt that nice , so from text, to format, to anything let me know and I'll fix it!

**Comment by emmairwin** [comment]
Please reopen if changes needed.
