### ISSUE TITLE
Social Media - Advanced Strategies

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/leadership_toolkit#18]
Standards and templates for developing content [can be found here](https://wiki.mozilla.org/Participation/Projects/Leadership_toolkit#Work_To_Date).

Title to indicate level of learning, but can be called anything of course.

**Comment by jgmac1106** [comment]
Here is link to file: https://github.com/emmairwin/leadership_toolkit/blob/master/social_media_advanced.md

**Comment by emmairwin** [comment]
Thanks @jgmac1106  to template:  https://docs.google.com/document/d/1tW_gUxwE3AkT90fr_w2KRVKJpYn1GobwgZHJOV3NGvA/edit#heading=h.vlsjbhbxf3bs

**Comment by emmairwin** [comment]
learning outcomes were approved, but no content started.  Closing  - will reopen if it is requested in new year.

**Comment by jgmac1106** [comment]
No problem. I never got to it. Apologies. Can return to it if necessary.
