### ISSUE TITLE
Combatting Unconscious Bias

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/leadership_toolkit#24]
Port existing content from Singapore

https://docs.google.com/document/d/14j01wx3CmswvtQjj725FPA4kJW-LbjJRzM5aWVw3Hvo/edit

**Comment by xellpher** [comment]
This links to Giving/receiving feedback, where bias is something a giver/receiver should get rid of.

**Comment by emmairwin** [comment]
We will be creating content for D&I next year, will reopen this, or create new tasks with that work.
