### ISSUE TITLE
Social Media 101

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/leadership_toolkit#28]
Proposed after reps-review  - where people start with social media.

**Comment by emmairwin** [comment]
What comes before advanced strategies

**Comment by verenanz1** [comment]
Standards and templates for developing content can be found here.

**Comment by emmairwin** [comment]
@verenanz1 are you still interested in taking this one?  If so, please re-open  0   closing since it was only proposed by our group (not requested from teams) and no work has started.

**Comment by verenanz1** [comment]
I can do it- but if no one asked for it, perhaps I should wait for an updated list ?

Emma, please tell me what you think would be best use of my time....

V:)
