### ISSUE TITLE
Giving Feedback 101  

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/leadership_toolkit#29]
From @xellpher 

I like the Johari Window, but am wondering whether it's a "Feedback 201" workshop? Maybe I'm looking at the toolkit from the point of view of a noob, but I think it would be a good idea to first introduce basic ideas and terminology (constructive, positive v. negative feedback/where, to whom, how to give the feedback/the formula of feedback+change=learning etc.) I'm afraid I don't have any resources for this (except in Finnish...), but I'll keep looking.

**Comment by emmairwin** [comment]
@xellpher do you have any content source we can use right away for this?  Would love to give it to Edouardo to test.

**Comment by emmairwin** [comment]
http://www.oercommons.org/courses/thumbs-up-signals-to-encourage-active-listening/view

**Comment by verenanz1** [comment]
Hello all -

I found some quick content on Giving Feedback 101:
https://www.uts.edu.au/sites/default/files/Giving-and-Receiving-Feedback.pdf
(It is NOT cc licensed though, so would have to link to it directly, not embed)

I also like this online resource (CC licensed) 
http://www.newconversations.net/communication-skills-workbook/from-complaints-to-requests/

V:)

**Comment by verenanz1** [comment]
I would assign this one to myself - but I am unsure of exactly how far it got?  I would add in the http://www.newconversations.net/communication-skills-workbook/from-complaints-to-requests/

Online resource as Feedback 101 in the initial stages of the workshop, then go with what we have?

V:)

**Comment by verenanz1** [comment]
Current Google doc on Giving and Receiving Feedback:
https://docs.google.com/document/d/1ky8srxMra_qfzlDNKFPaQ2eKwhODTJAFXkgKN-8PeDI/edit

**Comment by emmairwin** [comment]
@verenanz1 does this look like a fair and complete version of your proposal?   https://leadership.mozilla.community/method/giving-and-receiving-feedback/

**Comment by emmairwin** [comment]
This was published here https://leadership.mozilla.community/method/deep-listening/  
and Edouardo has tested once with 2 partcipants.
**Participant expectations:**
* could help me to understand and know my listening capacity level.
take me to a passive listening of the others more quickly

Participant feedback
* 3.5 of 5 rated helpful.
*  help me some in the exposition, especially to feel free to express my self.
* these ten aspects could be re-read some other times because frequently in our life we loose our-self and what was be taken for granted wasn't be in real. 
* I share all these topics that I just working personally.
He was constructive and open
